server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tourisminarmenia
    username: root
    password: root

  jpa:
    show-sql: true

  liquibase:
    change-log: classpath:/liquibase/changelog.xml

jwt:
  secret: YXNkZmYkIyNzZFNEU0RBQVNERksjQEBkc2ZqZGZrZHNqQEAjZHNmZ2ZnZmdeXiYmWipeJSQkI2RzZHMkIyVzZDQ1MDk5KUkjJCg5V0ZTSUo=
  expiration: 600000

upload:
  image:
    path: C:\\TourismInArmenia\\images\\

site:
  url: http://localhost:8081


logging:
  level:
    root=info:
